spring.application.name=PhoniixPortfolio

# Logging Configuration
logging.level.com.Phoniix.PhoniixPortfolio=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/portfolio.log
logging.file.max-size=10MB
logging.file.max-history=30
